- To install NumPy we run command:
```pip install numpy```

In [2]:
import numpy as np

- Creating an empty array

In [3]:
array_2d = np.empty((5,5))
print(array_2d)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.05700770e-307
  1.89146896e-307]
 [7.56571288e-307 3.11525958e-307 1.24610723e-306 1.37962320e-306
  1.29060871e-306]
 [2.22518251e-306 1.33511969e-306 1.78022342e-306 1.05700345e-307
  3.11525958e-307]
 [1.69118108e-306 8.06632139e-308 1.20160711e-306 1.69119330e-306
  1.29062229e-306]
 [1.29060531e-306 2.13620807e-306 1.69118787e-306 2.56765117e-312
  5.97819431e-322]]


```The full() function in NumPy creates an array of a given shape and fills it with a specified value.```

In [10]:
# full_array = np.full((5,5),6)
# We can also add attributes dtype in full function as well as empty function.
full_arrayEg = np.full((5,3),6, dtype=int)
print(full_arrayEg)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


```Numpy array filled with all zeros```

In [13]:
array_zeros = np.zeros((5,5),dtype=int)
print(array_zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


```Numpy array filled with all ones```

In [16]:
array_ones = np.ones((5,5),dtype=int)
print(array_ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


```Check whether a Numpy array contains a specified row```

- If the given list is present in a NumPy array as a row then the output is True else False.

In [26]:
array_creation = np.array([[12,21,2122,21212,211],[81,4304,59657,785,3232],[323,32,4324,3,4]])
print(array_creation)

print([12,21,2122,21212,211]in array_creation.tolist())
print([]in array_creation.tolist())
print([11, 12, 13, 14, 15]in array_creation.tolist())
print([323,32,4324,3,4]in array_creation.tolist())

[[   12    21  2122 21212   211]
 [   81  4304 59657   785  3232]
 [  323    32  4324     3     4]]
True
False
False
True


https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/

^^^^ To Be referred ^^^^